schema_version = 2

[package]
name = "glibc-dev"
version = "2.44"
release = "1"
arch = "amd64"
description = "GNU C Library headers, static libraries and linker scripts"
license = "LGPL-2.1-or-later"
channel = "system"

[source]
url = "https://mirrors.kernel.org/gnu/glibc/glibc-2.44.tar.xz"
sha256 = "37f600f2bef3c5e8300147059568b2a2e40a7ad6ccc65ce942556d49429cc667"

dependencies = [
    "glibc >= 2.44",
    "linux-headers >= 7.1.9"
]

build_dependencies = []

provides = [
    "glibc-dev"
]

[upstream]
url = "https://ftp.gnu.org/gnu/glibc/"
version_regex = 'glibc-([0-9][0-9.]*)\.tar'

[build]
system = "autotools"
source_subdir = ""
build_dir = "build"
install_targets = ["install"]
install_files = [
    "usr/include/**",
    "usr/lib/*.a",
    "usr/lib/*.so",
]
install_excludes = [
    "usr/lib/libanl.so",
    "usr/lib/libBrokenLocale.so",
    "usr/lib/libc_malloc_debug.so",
    "usr/lib/libmemusage.so",
    "usr/lib/libmvec.so",
    "usr/lib/libnss_compat.so",
    "usr/lib/libnss_db.so",
    "usr/lib/libnss_hesiod.so",
    "usr/lib/libpcprofile.so",
    "usr/lib/libthread_db.so",
]
configure_options = [
    "--enable-kernel=4.19",
    "--enable-stack-protector=strong",
    "--disable-profile",
    "--disable-werror",
    "--without-gd",
]

[build.variables]
libc_cv_slibdir = "/usr/lib"

[build.toolchain.compiler]
family = "gcc"
package = "gcc"
minimum_version = "16.2.0"
