schema_version = 1

[package]
name = "gawk"
version = "5.4.1"
release = 1
epoch = 0
description = "GNU pattern scanning and processing language utility (gawk)"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "mpfr-libs >= 4.2.2-1",
    "gmp >= 6.3.0-1",
    "readline >= 8.3-1",
]

provides = ["gawk", "virtual/awk", "awk"]

[source]
url = "https://ftp.gnu.org/gnu/gawk/gawk-5.4.1.tar.xz"
sha256 = "07f6f7342b7febe4313fc2c2542ad93d64fe20ad8717200109f105a826f5fd37"

[build]
inherit = ["autotools"]
dependencies = [
    "gmp-dev >= 6.3.0-1",
    "mpfr-dev >= 4.2.2-1",
    "readline-dev >= 8.3-1",
]

[build.args]
configure_args = "--with-mpfr --with-readline --disable-nls"

[build.payload]
default = "remaining"

[[alternatives]]
link = "usr/bin/awk"
target = "gawk"
priority = 50
