schema_version = 2

[package]
name = "grep"
version = "3.12"
release = "1"
arch = "amd64"
description = "GNU grep"
license = "GPL-3.0-or-later"
channel = "system"

dependencies = [
    "pcre2-libs >= 10.47"
]

build_dependencies = [
    "pcre2-dev >= 10.47"
]

provides = [
    "grep"
]

[upstream]
url = "https://ftp.gnu.org/gnu/grep/"
version_regex = 'grep-([0-9][0-9.]*)\.tar'

[source]
url = "https://mirrors.kernel.org/gnu/grep/grep-3.12.tar.xz"
sha256 = "2649b27c0e90e632eadcd757be06c6e9a4f48d941de51e7c0f83ff76408a07b9"

[build]
system = "autotools"
payload = "all"
install_targets = ["install"]
configure_options = [
    "--disable-nls"
]
