schema_version = 1

[package]
name = "btrfs-progs"
version = "7.1"
release = 1
epoch = 0
description = "Btrfs filesystem utilities and management commands (btrfs, mkfs.btrfs, btrfs-image)"
license = "GPL-2.0-only"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "btrfs-progs-libs >= 7.1-1",
    "util-linux-libs >= 2.42.2-1",
    "zlib-libs >= 1.3.2-1",
    "lzo-libs >= 2.10-1",
    "zstd-libs >= 1.5.7-1",
]

provides = ["btrfs-progs"]

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/kdave/btrfs-progs/btrfs-progs-v7.1.tar.xz"
sha256 = "66f7f32ce10df866412f122557bdfe6c810ebc2f42a17aa98fb7e9ffb55977fb"

[build]
inherit = ["autotools"]

[build.args]
configure_args = "--disable-documentation --disable-python --disable-backtrace"

[build.payload]
default = "remaining"

[[subpackages]]
name = "btrfs-progs-libs"
description = "Btrfs filesystem runtime shared library (libbtrfs, libbtrfsutil)"
license = "LGPL-2.1-or-later"
dependencies = [
    "virtual/libc",
]
provides = ["btrfs-progs-libs", "so:libbtrfs.so.0", "so:libbtrfsutil.so.1"]

[subpackages.payload]
files = [
    "usr/lib/*.so.*",
]

[[subpackages]]
name = "btrfs-progs-dev"
description = "Btrfs development headers and pkgconfig metadata"
license = "LGPL-2.1-or-later"
dependencies = [
    "btrfs-progs-libs >= 7.1-1",
]
provides = ["btrfs-progs-dev"]

[subpackages.payload]
files = [
    "usr/include/**",
    "usr/lib/*.a",
    "usr/lib/*.so",
    "usr/lib/pkgconfig/**",
]
