schema_version = 1

[package]
name = "linux-api-headers"
version = "7.1.11"
release = 1
epoch = 0
description = "Kernel headers sanitized for use in userspace"
license = "GPL-2.0-only WITH Linux-syscall-note"
channel = "system"
arch = "amd64"

dependencies = []

provides = [
    "linux-api-headers",
    "virtual/kernel-headers",
]

[source]
url = "https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.1.11.tar.xz"
sha256 = "3029540d8f2ec75bee5cbdb7c2a0daa60bffa1d105c82ecb99b53432f6351afc"

[build]
inherit = ["custom"]

[build.args]
install_cmd = """
make -C "${SRC_DIR}" headers_install INSTALL_HDR_PATH="${DESTDIR}/usr"
"""

[build.payload]
default = "remaining"
