schema_version = 1

[package]
name = "shadow"
version = "4.20.2"
release = 1
epoch = 0
description = "Password and account management utilities (passwd, useradd, usermod, login, su)"
license = "BSD-3-Clause"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "libxcrypt-libs >= 4.5.2-1",
    "libseccomp-libs >= 2.6.0-1",
]

provides = ["shadow", "virtual/login"]

[source]
url = "https://github.com/shadow-maint/shadow/releases/download/v4.20.2/shadow-4.20.2.tar.xz"
sha256 = "66f7f32ce10df866412f122557bdfe6c810ebc2f42a17aa98fb7e9ffb55977fb"

[build]
inherit = ["autotools"]

[build.args]
configure_args = "--sysconfdir=/etc --without-libpam --with-bcrypt --with-yescrypt --disable-nls --with-libsubid=no"

[build.payload]
default = "remaining"
