schema_version = 1

[package]
name = "shadow"
version = "4.20.2"
release = 1
epoch = 0
description = "Password and account management utilities (passwd, useradd, usermod, login, su)"
license = "BSD-3-Clause"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "libxcrypt-libs >= 4.5.2-1",
    "libseccomp-libs >= 2.6.0-1",
]

provides = ["shadow", "virtual/login"]

[source]
url = "https://github.com/shadow-maint/shadow/releases/download/4.20.2/shadow-4.20.2.tar.gz"
sha256 = "e5016b40541ee6fa02ea3d409547cef6e7eea9b31f0e3482e4874f87c1d0c7c5"

[build]
inherit = ["autotools"]

[build.args]
configure_args = "--sysconfdir=/etc --without-libpam --with-bcrypt --with-yescrypt --disable-nls --with-libsubid=no --without-libbsd"

[build.payload]
default = "remaining"
