schema_version = 1

[package]
name = "linux-aarch64-headers"
version = "7.2"
release = "1"
arch = "aarch64"
description = "Linux AArch64 userspace API headers"
license = "GPL-2.0-only"
channel = "system"

dependencies = []

provides = [
    "linux-aarch64-headers",
    "linux-headers",
    "virtual/linux-headers",
]

prepare = []

build = [
    "make ARCH=arm64 headers",
]

install = [
    "find usr/include -type f ! -name '*.h' -delete",
    "mkdir -p $DESTDIR/usr/include",
    "cp -rv usr/include/* $DESTDIR/usr/include/",
]

[source]
url = "https://cdn.kernel.org/pub/linux/kernel/v7.x/linux-7.2.tar.xz"
sha256 = "f9fef3d14c0df53819026f4be74459835c2a0b0dcbf5b5bbd9ea19f0829402b3"
