schema_version = 1

[package]
name = "fakeroot"
version = "2.1.4"
release = 1
epoch = 0
description = "Gives a fake root environment by wrapping file manipulation syscalls"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
]

provides = ["fakeroot"]

[source]
url = "https://deb.debian.org/debian/pool/main/f/fakeroot/fakeroot_2.1.4.orig.tar.xz"
sha256 = "0822bd5a9f0cf19d2ba0546b88b0432d4d3d9917db62c57b74044ccadba06e49"
strip_components = 1
destination = "."

[build]
inherit = ["custom"]
dependencies = [
    "system/autoconf",
    "system/automake",
    "system/libtool",
    "system/make",
    "system/pkgconf",
]

[build.args]
install_cmd = 'cd "${SRC_DIR}"; ./bootstrap; ./configure --prefix=/usr; make -j"${JOBS}"; make DESTDIR="${DESTDIR}" install'

[build.payload]
default = "remaining"
