schema_version = 2

[package]
name = "e2fsprogs"
version = "1.47.4"
release = "1"
arch = "amd64"
description = "Ext2/3/4 filesystem utilities"
license = "GPL-2.0-or-later"
channel = "system"
dependencies = [
    "e2fsprogs-libs >= 1.47.4",
    "util-linux-libs >= 2.42.2"
]
build_dependencies = [
    "pkgconf >= 3.0.5"
]
provides = [
    "e2fsprogs"
]

[upstream]
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.4/"
version_regex = 'e2fsprogs-v?([0-9][0-9.]*)\.tar'

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.4/e2fsprogs-1.47.4.tar.xz"
sha256 = "fd5bf388cbdbe006a3d3b318d983b2948382440acc85a87f1e7d108653e8db0b"

[build]
system = "autotools"
payload = "allowlist"
install_files = ["**"]
install_targets = ["install"]
install_excludes = [
    "usr/include/**",
    "usr/lib/*.a",
    "usr/lib/*.so",
    "usr/lib/*.so.*",
    "usr/lib/pkgconfig/**",
    "usr/lib/cmake/**",
    "usr/share/aclocal/**",
    "usr/share/pkgconfig/**",
]
configure_options = [
    "--sysconfdir=/etc",
    "--enable-elf-shlibs",
    "--disable-libblkid",
    "--disable-libuuid",
    "--disable-uuidd",
    "--disable-fsck",
]
