schema_version = 2

[package]
name = "e2fsprogs"
version = "1.47.4"
release = "1"
arch = "amd64"
description = "Ext2/3/4 filesystem utilities"
license = "GPL-2.0-or-later"
channel = "system"
dependencies = [
    "e2fsprogs-libs >= 1.47.4",
    "util-linux-libs >= 2.42.2"
]
build_dependencies = [
    "pkgconf >= 3.0.5",
    "util-linux-dev >= 2.42.2"
]
provides = [
    "e2fsprogs"
]

[upstream]
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.4/"
version_regex = 'e2fsprogs-v?([0-9][0-9.]*)\.tar'

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.4/e2fsprogs-1.47.4.tar.xz"
sha256 = "fd5bf388cbdbe006a3d3b318d983b2948382440acc85a87f1e7d108653e8db0b"

[build]
system = "autotools"
payload = "outputs"
install_targets = ["install", "install-libs"]
configure_options = [
    "--sysconfdir=/etc",
    "--enable-elf-shlibs",
    "--disable-libblkid",
    "--disable-libuuid",
    "--disable-uuidd",
    "--disable-fsck",
]

[[build.outputs]]
name = "e2fsprogs"
description = "Ext2/3/4 filesystem utilities"
license = "GPL-2.0-or-later"
dependencies = [
    "e2fsprogs-libs >= 1.47.4",
    "util-linux-libs >= 2.42.2"
]
provides = [
    "e2fsprogs"
]
install_files = [
    "etc/**",
    "usr/bin/**",
    "usr/sbin/**",
    "usr/share/doc/**",
    "usr/share/locale/**",
    "usr/share/man/man1/**",
    "usr/share/man/man5/**",
    "usr/share/man/man8/**",
]
optional_excludes = [
    "etc/**",
    "usr/share/doc/**",
    "usr/share/locale/**",
    "usr/share/man/man1/**",
]

[[build.outputs]]
name = "e2fsprogs-libs"
description = "libext2fs/libcom_err/libss runtime libraries"
license = "LGPL-2.1-or-later"
dependencies = [
    "util-linux-libs >= 2.42.2"
]
provides = [
    "e2fsprogs-libs",
    "so:libext2fs.so.2",
    "so:libcom_err.so.2",
    "so:libss.so.2"
]
install_files = [
    "usr/lib/*.so.*",
]

[[build.outputs]]
name = "e2fsprogs-dev"
description = "e2fsprogs library headers, pkg-config and linker symlink"
license = "LGPL-2.1-or-later"
dependencies = [
    "e2fsprogs-libs >= 1.47.4"
]
provides = [
    "e2fsprogs-dev"
]
install_files = [
    "usr/include/**",
    "usr/lib/*.a",
    "usr/lib/*.so",
    "usr/lib/pkgconfig/**",
    "usr/lib/cmake/**",
    "usr/share/aclocal/**",
    "usr/share/pkgconfig/**",
    "usr/share/man/man3/**",
]
optional_excludes = [
    "usr/lib/*.a",
    "usr/lib/cmake/**",
    "usr/share/aclocal/**",
    "usr/share/pkgconfig/**",
    "usr/share/man/man3/**",
]
