schema_version = 2

[package]
name = "kbd"
version = "2.10.0"
release = "1"
arch = "amd64"
description = "Keyboard and console utilities"
license = "GPL-2.0-or-later"
channel = "system"
dependencies = [
]
build_dependencies = [
    "linux-headers >= 7.1.9",
    "flex >= 2.6.4"
]
provides = [
    "kbd"
]

[upstream]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/kbd/"
version_regex = 'kbd-v?([0-9][0-9.]*)\.tar'

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/kbd/kbd-2.10.0.tar.xz"
sha256 = "6e5ca4f8d76ee9e3a8db700b667f13e12aac9933828a64e1aaad93d26be9b479"

[build]
system = "autotools"
configure_options = [
    "--disable-vlock"
]
