schema_version = 1

[package]
name = "pahole"
version = "1.31"
release = 1
epoch = 0
description = "DWARF and BTF debugging information inspection tools"
license = "GPL-2.0-or-later"
channel = "system"
arch = "amd64"

dependencies = ["virtual/libc", "libelf-libs", "zlib-libs"]
provides = ["pahole"]

[[sources]]
url = "https://fedorapeople.org/~acme/dwarves/dwarves-1.31.tar.xz"
sha256 = "0a7f255ccacf8cc7f8cd119099eb327179b4b3c67cb015af646af6d0cb03054d"
strip_components = 1
destination = "."

[build]
inherit = ["cmake"]
dependencies = ["libelf-dev", "zlib-dev"]

[build.args]
cmake_args = "-D__LIB=lib -D__LIB64=lib -DWITH_TESTS=OFF -DWITH_BPF=ON"

[build.payload]
default = "remaining"
