schema_version = 2

[package]
name = "expect"
version = "5.45.4"
release = "1"
description = "Automate interactive applications"
license = "Public-domain"
channel = "system"
arch = "amd64"
dependencies = [
    "tcl-libs >= 8.6.18"
]
build_dependencies = [
    "tcl-dev >= 8.6.18"
]
provides = [
    "expect",
    "so:libexpect5.45.4.so"
]

[upstream]
url = "https://sourceforge.net/projects/expect/files/Expect/"
version_regex = '([0-9.]+)/'

[source]
url = "https://downloads.sourceforge.net/project/expect/Expect/5.45.4/expect5.45.4.tar.gz"
sha256 = "49a7da83b0bdd9f46d04a04deec19c7767bb9a323e40c4781f89caf760b92c34"

[build]
system = "autotools"
payload = "all"
install_targets = ["install"]
configure_options = [
    "--with-tcl=/usr/lib",
    "--enable-shared",
    "--mandir=/usr/share/man",
    "--with-tclinclude=/usr/include",
]
