schema_version = 1

[package]
name = "which"
version = "2.25"
release = 1
epoch = 0
description = "Utility that prints the full path of executables found in PATH"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
]

provides = ["which"]

[source]
url = "https://ftp.gnu.org/gnu/which/which-2.25.tar.gz"
sha256 = "1cb83e4f702e60b8211ab5ec4c2afbab1b1dec80209456a7d2faf7584ed225ea"

[build]
inherit = ["autotools"]

[build.payload]
default = "remaining"
