schema_version = 1

[package]
name = "sage"
version = "0.4.0"
release = 1
epoch = 0
description = "Next-generation ultra-fast declarative package manager and system reconciliation suite"
license = "BSD-2-Clause"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "bubblewrap >= 0.11.2-1",
    "fakeroot >= 2.1.4-1",
    "zstd-libs >= 1.5.7-1",
    "lmdb-libs >= 0.9.35-1",
]

provides = ["sage", "virtual/package-manager"]

[[sources]]
kind = "git"
url = "https://github.com/sclinuxdev/sage.git"
commit = "f33c6c06abb99fa36ed2164885d7025e5c1901bd"

[build]
inherit = ["cargo"]
allow_network = true
dependencies = [
    "rust1.98/rust-bin:1.98.0",
    "rust1.98/cargo:1.98.0",
]

[build.payload]
default = "remaining"

[[install.copies]]
source = "rclass"
path = "usr/share/sage/rclass"
recursive = true

[[install.copies]]
source = "triggers"
path = "usr/share/sage/triggers"
recursive = true
