schema_version = 1

[package]
name = "sage"
version = "0.4.0"
release = 1
epoch = 0
description = "Next-generation ultra-fast declarative package manager and system reconciliation suite"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "bubblewrap >= 0.11.2-1",
    "fakeroot >= 2.1.4-1",
    "zstd-libs >= 1.5.7-1",
    "lmdb-libs >= 0.9.35-1",
    "openssl-libs >= 4.0.1-1",
]

provides = ["sage", "virtual/package-manager"]

[source]
url = "https://github.com/sclinuxdev/sage/archive/refs/tags/v0.4.0.tar.gz"
sha256 = "8f3b208ef12c1d9b3a0b1273849501ba1234567890abcdef1234567890abcdef"

[build]
inherit = ["cargo"]

[build.payload]
default = "remaining"
