schema_version = 2

[package]
name = "e2fsprogs-libs"
version = "1.47.4"
release = "1"
description = "libext2fs/libcom_err/libss runtime libraries"
license = "LGPL-2.1-or-later"
channel = "system"
arch = "amd64"
dependencies = [
    "util-linux-libs >= 2.42.2"
]
build_dependencies = [
    "pkgconf >= 3.0.5",
    "util-linux-dev >= 2.42.2"
]
provides = [
    "e2fsprogs-libs",
    "so:libext2fs.so.2",
    "so:libcom_err.so.2",
    "so:libss.so.2"
]

[upstream]
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.4/"
version_regex = 'e2fsprogs-libs-v?([0-9][0-9.]*)\.tar'

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/kernel/people/tytso/e2fsprogs/v1.47.4/e2fsprogs-1.47.4.tar.xz"
sha256 = "fd5bf388cbdbe006a3d3b318d983b2948382440acc85a87f1e7d108653e8db0b"

[build]
system = "autotools"
payload = "allowlist"
install_files = [
    "usr/lib/*.so.*",
]
configure_options = [
    "--sysconfdir=/etc",
    "--enable-elf-shlibs",
    "--disable-libblkid",
    "--disable-libuuid",
    "--disable-uuidd",
    "--disable-fsck",
]
build_targets = [
    "libs",
]
install_targets = [
    "install-libs",
]
