schema_version = 1

[package]
name = "dbus"
version = "1.16.2"
release = 1
epoch = 0
description = "Freedesktop simple interprocess messaging system daemon"
license = "AFL-2.1 OR GPL-2.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
    "dbus-libs >= 1.16.2-1",
    "expat-libs >= 2.8.3-1",
]

provides = ["dbus", "virtual/dbus"]

[source]
url = "https://dbus.freedesktop.org/releases/dbus/dbus-1.16.2.tar.xz"
sha256 = "0ba2a1a4b16afe7bceb2c07e9ce99a8c2c3508e5dec290dbb643384bd6beb7e2"

[build]
inherit = ["meson"]

[build.args]
meson_args = "-Dsystem_socket=/run/dbus/system_bus_socket -Dxml_library=expat -Dsession_socket_dir=/tmp"

[build.payload]
default = "remaining"

[[subpackages]]
name = "dbus-libs"
description = "D-Bus low-level runtime client shared library (libdbus-1.so.*)"
license = "AFL-2.1 OR GPL-2.0-or-later"
dependencies = [
    "virtual/libc",
]
provides = ["dbus-libs", "so:libdbus-1.so.3"]

[subpackages.payload]
files = [
    "usr/lib/*.so.*",
]

[[subpackages]]
name = "dbus-dev"
description = "D-Bus development headers, pkgconfig and cmake files"
license = "AFL-2.1 OR GPL-2.0-or-later"
dependencies = [
    "dbus-libs >= 1.16.2-1",
]
provides = ["dbus-dev"]

[subpackages.payload]
files = [
    "usr/include/dbus-1.0/**",
    "usr/lib/dbus-1.0/include/**",
    "usr/lib/*.so",
    "usr/lib/pkgconfig/**",
    "usr/lib/cmake/**",
]

[[sysusers]]
type = "user"
name = "messagebus"
id = 18
description = "D-Bus Message Daemon User"
home = "/run/dbus"
shell = "/usr/bin/nologin"
