schema_version = 1

[package]
name = "ninja"
version = "1.13.2"
release = 1
epoch = 0
description = "Small and fast build system"
license = "Apache-2.0"
channel = "system"
arch = "amd64"

dependencies = ["virtual/libc"]
provides = ["ninja"]

[[sources]]
url = "https://github.com/ninja-build/ninja/archive/refs/tags/v1.13.2.tar.gz"
sha256 = "974d6b2f4eeefa25625d34da3cb36bdcebe7fbce40f4c16ac0835fd1c0cbae17"
strip_components = 1
destination = "."

[build]
inherit = ["custom"]
dependencies = ["python3.14/python:3.14"]

[build.args]
install_cmd = "python3 configure.py --bootstrap; install -Dm755 ninja \"${DESTDIR}/usr/bin/ninja\""

[build.payload]
default = "remaining"
