schema_version = 2

[package]
name = "util-linux-libs"
version = "2.42.2"
release = "1"
arch = "amd64"
description = "libuuid/libblkid/libmount/libsmartcols/libfdisk runtime libraries"
license = "LGPL-2.1-or-later"
channel = "system"
dependencies = []
build_dependencies = [
    "sqlite-dev >= 3.53.4"
]
provides = [
    "util-linux-libs",
    "so:libuuid.so.1",
    "so:libblkid.so.1",
    "so:libmount.so.1",
    "so:libsmartcols.so.1",
    "so:libfdisk.so.1"
]

[upstream]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.42/"
version_regex = 'util-linux-libs-v?([0-9][0-9.]*)\.tar'

[source]
url = "https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/v2.42/util-linux-2.42.2.tar.xz"
sha256 = "03a05d3adf9602ef128f2da05b84b3205ce60c351e5737c0370f74000679ce8a"

[build]
system = "autotools"
install_targets = ["install"]
install_files = [
    "usr/lib/*.so.*",
]
configure_options = [
    "--disable-static",
    "--without-python",
    "--without-systemd",
    "--disable-liblastlog2",
    "--disable-pam-lastlog2",
    "--disable-all-programs",
    "--enable-libmount",
    "--enable-libuuid",
    "--enable-libblkid",
    "--enable-libsmartcols",
    "--enable-libfdisk"
]
