schema_version = 1

[package]
name = "gzip"
version = "1.14"
release = 1
epoch = 0
description = "GNU standard compression and decompression utility"
license = "GPL-3.0-or-later"
channel = "system"
arch = "amd64"

dependencies = [
    "virtual/libc",
]

provides = ["gzip"]

[source]
url = "https://ftp.gnu.org/gnu/gzip/gzip-1.14.tar.xz"
sha256 = "66f7f32ce10df866412f122557bdfe6c810ebc2f42a17aa98fb7e9ffb55977fb"

[build]
inherit = ["autotools"]

[build.payload]
default = "remaining"
