schema_version = 1

[package]
name = "pkgconf"
version = "3.0.5"
release = 1
epoch = 0
description = "Package compiler and linker metadata tool"
license = "ISC"
channel = "system"
arch = "amd64"

dependencies = ["virtual/libc"]
provides = ["pkgconf", "pkg-config"]

[[sources]]
url = "https://distfiles.ariadne.space/pkgconf/pkgconf-3.0.5.tar.xz"
sha256 = "3acd3a8a3cce65a8d620321855d92fb602e026cbe8e13ee36bdec58483b59ace"
strip_components = 1
destination = "."

[build]
inherit = ["custom"]
dependencies = ["system/make"]

[build.args]
install_cmd = """
cd "${SRC_DIR}"
./configure --prefix=/usr --disable-static --with-system-includedir=/usr/include --with-system-libdir=/usr/lib
make -j"${JOBS}"
make DESTDIR="${DESTDIR}" install
ln -s pkgconf "${DESTDIR}/usr/bin/pkg-config"
"""

[build.payload]
default = "remaining"
