schema_version = 2

[package]
name = "zsh"
version = "5.9.2"
release = "1"
arch = "amd64"
description = "Z shell, an interactive shell with advanced completion, themable prompts and scripting extensions"
license = "Zsh"
channel = "system"
dependencies = [
    "ncurses-libs >= 6.6",
    "ncurses-terminfo >= 6.6"
]
build_dependencies = [
    "ncurses-dev >= 6.6"
]
provides = [
    "zsh"
]

[upstream]
url = "https://www.zsh.org/pub/"
version_regex = 'zsh-([0-9]+\.[0-9.]+)\.tar'

[source]
url = "https://www.zsh.org/pub/zsh-5.9.2.tar.xz"
sha256 = "36fa734374b44783582cec09bcd67822e2f992c779ec1624ab5596df078d2f81"

[build]
system = "autotools"
configure_options = [
    "--enable-multibyte",
    "--with-term-lib=ncursesw",
]
